### ISSUE TITLE
Nomethoderror: undefined method `return' for Timecop:Class when running `db:reset`

### ISSUE THREAD

**Issue by lakshmivyas** [openstax/tutor-server#309]
Stacktrace:
```
stderr: rake aborted!
NoMethodError: undefined method `return' for Timecop:Class
/home/osttutor/src/tutor-913f30c/config/initializers/timecop.rb:18:in `load_time'
/home/osttutor/src/tutor-913f30c/config/initializers/timecop.rb:24:in `<top (required)>'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/engine.rb:652:in `block in load_config_initializer'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/notifications.rb:166:in `instrument'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/engine.rb:651:in `load_config_initializer'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/engine.rb:615:in `each'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/engine.rb:615:in `block in <class:Engine>'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `each'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `tsort_each_child'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
/home/osttutor/src/tutor-913f30c/config/environment.rb:19:in `<top (required)>'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/application.rb:328:in `require_environment!'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/application.rb:443:in `block in run_tasks_blocks'
Tasks: TOP => db:reset => environment
(See full trace by running task with --trace)
```

**Comment by jpslav** [comment]
@Dantemss possible name collision with the real `Timecop`?

**Comment by jpslav** [comment]
Oh I see that you just reopened the class.  Wonder if this rake task is loading the initializer before the gem and then not finding the class in the gem...

**Comment by jpslav** [comment]
I can't replicate this error by running `bundle exec rake db:reset`.  @lakshmivyas if you get it to repeat, you might try a `require 'timecop'` at the top of `config/initializers/timecop.rb`

**Comment by lakshmivyas** [comment]
Ah, its because timecop is added to development gem list - we don't use that on deployment.

**Comment by Dantemss** [comment]
Oh right... guess it needs to be added to demo too.
